# Matrix multiplication from first principles
>### Note: The code below works only for square matrices

In [33]:
import random

## Functions to create matrices (including the null matrix)

In [34]:
def create_matrix(rows, cols):
    return [[random.randint(0, 9) for c in range(cols)] for r in range(rows)]

def create_null_matrix(rows, cols):
    return [[0 for c in range(cols)] for r in range(rows)]

## Define matrix dimensions
>(optional step) Take input from user for the number of rows and columns in the matrices

In [35]:
# Take user input (optional)
# rows = int(input("Number of rows: "))
# cols = int(input("Number of columns: "))

# Default values
rows = 3
cols = 3

## Create matrices

In [36]:
a = create_matrix(rows, cols)
b = create_matrix(rows, cols)

print(a)
print(b)

c = create_null_matrix(rows, cols)
print(c)

[[3, 5, 3], [5, 7, 9], [0, 1, 6]]
[[5, 0, 5], [1, 7, 5], [8, 8, 3]]
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]


## Matrix multiplication executed using ***"nested for loops"***
>***Note: The code below works only for square matrices***

In [37]:
for i in range(rows):
    for j in range(cols):
        for k in range(cols):
            c[i][j] = c[i][j] + a[i][k]*b[k][j]
print(c)

[[44, 59, 49], [104, 121, 87], [49, 55, 23]]


## Verify the result with numpy

In [39]:
import numpy

In [40]:
x = numpy.mat(a)
y = numpy.mat(b)

print(x*y)

[[ 44  59  49]
 [104 121  87]
 [ 49  55  23]]
